version: "2"
linters:
  default: all
  disable:
    - bodyclose
    - cyclop
    - depguard
    - dogsled
    - errcheck
    - errorlint
    - errname
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocyclo
    - gocognit
    - godot
    - gosec
    - gomoddirectives
    - ireturn
    - mnd
    - nestif
    - nlreturn
    - noctx
    - nonamedreturns
    - perfsprint
    - revive
    - tagalign
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
  
  settings:
    lll:
      line-length: 180
    predeclared:
      ignore:
        - new
    staticcheck:
      checks:
        - all
        - "-ST1000" # https://staticcheck.dev/docs/checks/#ST1000
        - "-ST1001" # https://staticcheck.dev/docs/checks/#ST1001
        - "-ST1020" # https://staticcheck.dev/docs/checks/#ST1020
        - "-ST1022" # https://staticcheck.dev/docs/checks/#ST1022