FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY . .

RUN go build -a -o ./bin/server .

FROM ubuntu:22.04 AS runner

WORKDIR /app

COPY --from=builder /app/bin/ .

EXPOSE 8080

ENTRYPOINT ["./server"]