// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package contracts

import (
	"context"
	"tasklist/modules/users/api/v1/models"

	elemental "github.com/elcengine/elemental/core"
	fq "github.com/elcengine/elemental/plugins/filterquery"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateUser(ctx context.Context, user models.User) models.User {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 models.User
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.User) models.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	return r0
}

// MockRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user models.User
func (_e *MockRepository_Expecter) CreateUser(ctx interface{}, user interface{}) *MockRepository_CreateUser_Call {
	return &MockRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockRepository_CreateUser_Call) Run(run func(ctx context.Context, user models.User)) *MockRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.User
		if args[1] != nil {
			arg1 = args[1].(models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateUser_Call) Return(user1 models.User) *MockRepository_CreateUser_Call {
	_c.Call.Return(user1)
	return _c
}

func (_c *MockRepository_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user models.User) models.User) *MockRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserByID provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteUserByID(ctx context.Context, id string) models.User {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserByID")
	}

	var r0 models.User
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	return r0
}

// MockRepository_DeleteUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserByID'
type MockRepository_DeleteUserByID_Call struct {
	*mock.Call
}

// DeleteUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) DeleteUserByID(ctx interface{}, id interface{}) *MockRepository_DeleteUserByID_Call {
	return &MockRepository_DeleteUserByID_Call{Call: _e.mock.On("DeleteUserByID", ctx, id)}
}

func (_c *MockRepository_DeleteUserByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_DeleteUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteUserByID_Call) Return(user models.User) *MockRepository_DeleteUserByID_Call {
	_c.Call.Return(user)
	return _c
}

func (_c *MockRepository_DeleteUserByID_Call) RunAndReturn(run func(ctx context.Context, id string) models.User) *MockRepository_DeleteUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUserByEmail(ctx context.Context, email string) *models.User {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *models.User
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	return r0
}

// MockRepository_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockRepository_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockRepository_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockRepository_GetUserByEmail_Call {
	return &MockRepository_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockRepository_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockRepository_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetUserByEmail_Call) Return(user *models.User) *MockRepository_GetUserByEmail_Call {
	_c.Call.Return(user)
	return _c
}

func (_c *MockRepository_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) *models.User) *MockRepository_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUserByID(ctx context.Context, id string, plain ...bool) *models.User {
	var tmpRet mock.Arguments
	if len(plain) > 0 {
		tmpRet = _mock.Called(ctx, id, plain)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.User
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...bool) *models.User); ok {
		r0 = returnFunc(ctx, id, plain...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	return r0
}

// MockRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - plain ...bool
func (_e *MockRepository_Expecter) GetUserByID(ctx interface{}, id interface{}, plain ...interface{}) *MockRepository_GetUserByID_Call {
	return &MockRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID",
		append([]interface{}{ctx, id}, plain...)...)}
}

func (_c *MockRepository_GetUserByID_Call) Run(run func(ctx context.Context, id string, plain ...bool)) *MockRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []bool
		var variadicArgs []bool
		if len(args) > 2 {
			variadicArgs = args[2].([]bool)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRepository_GetUserByID_Call) Return(user *models.User) *MockRepository_GetUserByID_Call {
	_c.Call.Return(user)
	return _c
}

func (_c *MockRepository_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id string, plain ...bool) *models.User) *MockRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUsers(ctx context.Context, fqr fq.Result) elemental.PaginateResult[models.User] {
	ret := _mock.Called(ctx, fqr)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 elemental.PaginateResult[models.User]
	if returnFunc, ok := ret.Get(0).(func(context.Context, fq.Result) elemental.PaginateResult[models.User]); ok {
		r0 = returnFunc(ctx, fqr)
	} else {
		r0 = ret.Get(0).(elemental.PaginateResult[models.User])
	}
	return r0
}

// MockRepository_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockRepository_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - fqr fq.Result
func (_e *MockRepository_Expecter) GetUsers(ctx interface{}, fqr interface{}) *MockRepository_GetUsers_Call {
	return &MockRepository_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, fqr)}
}

func (_c *MockRepository_GetUsers_Call) Run(run func(ctx context.Context, fqr fq.Result)) *MockRepository_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 fq.Result
		if args[1] != nil {
			arg1 = args[1].(fq.Result)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetUsers_Call) Return(paginateResult elemental.PaginateResult[models.User]) *MockRepository_GetUsers_Call {
	_c.Call.Return(paginateResult)
	return _c
}

func (_c *MockRepository_GetUsers_Call) RunAndReturn(run func(ctx context.Context, fqr fq.Result) elemental.PaginateResult[models.User]) *MockRepository_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserByID provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateUserByID(ctx context.Context, id string, user models.User) models.User {
	ret := _mock.Called(ctx, id, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserByID")
	}

	var r0 models.User
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.User) models.User); ok {
		r0 = returnFunc(ctx, id, user)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	return r0
}

// MockRepository_UpdateUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserByID'
type MockRepository_UpdateUserByID_Call struct {
	*mock.Call
}

// UpdateUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - user models.User
func (_e *MockRepository_Expecter) UpdateUserByID(ctx interface{}, id interface{}, user interface{}) *MockRepository_UpdateUserByID_Call {
	return &MockRepository_UpdateUserByID_Call{Call: _e.mock.On("UpdateUserByID", ctx, id, user)}
}

func (_c *MockRepository_UpdateUserByID_Call) Run(run func(ctx context.Context, id string, user models.User)) *MockRepository_UpdateUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.User
		if args[2] != nil {
			arg2 = args[2].(models.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateUserByID_Call) Return(user1 models.User) *MockRepository_UpdateUserByID_Call {
	_c.Call.Return(user1)
	return _c
}

func (_c *MockRepository_UpdateUserByID_Call) RunAndReturn(run func(ctx context.Context, id string, user models.User) models.User) *MockRepository_UpdateUserByID_Call {
	_c.Call.Return(run)
	return _c
}
